// <auto-generated />
namespace Log4Pro.IS.TRM.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Part_Entity_Add_SupplierShippingUnitQty_Field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Part_Entity_Add_SupplierShippingUnitQty_Field));
        
        string IMigrationMetadata.Id
        {
            get { return "201911151307541_Part_Entity_Add_SupplierShippingUnitQty_Field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
